services:
  - type: web
    name: quora-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      playwright install
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    plan: free
